version: 1.0

logging:
  level: "info"
  console: false # printing log to console is only supported in development mode

server_chain:
  id: "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe"
  signature_scheme: "bls0chain"

port: 9091

miners:
  - http://one.devnet-0chain.net:31201
  - http://one.devnet-0chain.net:31202
  - http://one.devnet-0chain.net:31203
  - http://one.devnet-0chain.net:31204
  - http://one.devnet-0chain.net:31205
  - http://one.devnet-0chain.net:31206
sharders:
  - http://one.devnet-0chain.net:31101
  - http://one.devnet-0chain.net:31102
  - http://one.devnet-0chain.net:31103

mongo:
  url: mongodb://mongodb:27017
  db_name: block-recorder
  pool_size: 2

worker:
  round_fetch_delay: 250 # in milliseconds