version: "3"

networks:
    default:
      driver: bridge
    testnet0:
      external: true
      
services:

  backend:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: backend
    volumes:
      - /opt/node_modules
      - .:/opt
    restart: always
    networks:
      default:
      testnet0:
    ports:
      - 3000:3000
    command: ["make", "dev-server"]


