version: "3"

volumes:
  mongo-data-0-0:
  mongo-data-0-1:
  mongo-data-0-2:

services:
  mongo0-0:
    image: mongo
    volumes:
      - mongo-data-0-0:/data/db
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo1-0:
    image: mongo
    volumes:
      - mongo-data-0-1:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2-0:
    image: mongo
    volumes:
      - mongo-data-0-2:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  backend:
    build: .
    volumes:
      - .:/opt
    restart: always
    ports:
      - 3000:3000
networks:
  default:
