name: Dockerize

on:
   push:
     branches: [ gitactionsfix ]

env:
  SEARCH_REGISTRY: 0blockworkreg/0blockwork

jobs:
   dockerize_backend:
       runs-on: ubuntu-20.04
       steps:
       - uses: actions/checkout@v2

       - name: Get the version
         id: get_version
         run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)    

           # - name: Login to Docker Hub
           #   uses: docker/login-action@v1
           #   with:
           #     username: ${{ secrets.DOCKERHUB_USERNAME }}
           #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build backend
         run: |
            docker build -t $SEARCH_REGISTRY:$TAG -f "$DOCKERFILE_BACKEND" .
           # docker push $SEARCH_REGISTRY:$TAG
         env:
           TAG: ${{ steps.get_version.outputs.VERSION }}
           DOCKERFILE_BACKEND: "./Dockerfile"
           
   dockerize_blockworker:
       runs-on: ubuntu-20.04
       steps:
       - uses: actions/checkout@v1

       - name: Get the version
         id: get_version
         run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)    

           # - name: Login to Docker Hub
           #   uses: docker/login-action@v1
           #   with:
           #     username: ${{ secrets.DOCKERHUB_USERNAME }}
           #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build backend
         run: |
            docker build -t $SEARCH_REGISTRY:$TAG -f "$DOCKERFILE_BLOCKWORK" .
           # docker push $SEARCH_REGISTRY:$TAG
         env:
           TAG: ${{ steps.get_version.outputs.VERSION }}
           DOCKERFILE_BLOCKWORK: "blockworker/docker.local/Dockerfile"
