name: Dockerize

on:
  workflow_dispatch:
    inputs:
      latest_tag:
        description: 'type yes for building latest tag'
        default: 'no'
        required: true

env:
  SEARCH_REGISTRY: 0search/0search

jobs:
   zsearch:
       runs-on: ubuntu-20.04
       steps:
       - uses: actions/checkout@v2    

       - name: Get the version
         id: get_version
         run: |
            BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
            SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)
            echo ::set-output name=BRANCH::${BRANCH}
            echo ::set-output name=VERSION::${BRANCH}-${SHORT_SHA} 
            
#        - name: Login to Docker Hub
#          uses: docker/login-action@v1
#          with:
#             username: ${{ secrets.DOCKERHUB_USERNAME }}
#             password: ${{ secrets.DOCKERHUB_PASSWORD }}

       - name: Build backend
         run: |
            docker build -t $SEARCH_REGISTRY:$TAG -f "$DOCKERFILE_BACKEND" .
            docker tag $SEARCH_REGISTRY:$TAG $SEARCH_REGISTRY:latest
         env:
           TAG: ${{ steps.get_version.outputs.VERSION }}
           DOCKERFILE_BACKEND: "./Dockerfile"

#        - name: Push image
#          run: |
#            if [[ "$PUSH_LATEST" == "yes" ]]; then
#              docker push $SEARCH_REGISTRY:latest
#            else
#              docker push $SEARCH_REGISTRY:$TAG
#            fi
#          env:
#            PUSH_LATEST: ${{ github.event.inputs.latest_tag }}
#            TAG: ${{ steps.get_version.outputs.VERSION }}
